os:
  - linux

before_install:
  - sudo apt-get install git-svn

language: csharp
mono: none
dotnet: 2.0.0
script:
 - chmod +x build.sh
 - chmod +x test.sh
 - chmod +x package.sh
 - ./build.sh
 - ./test.sh
 - ./package.sh

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
   - "ubuntu.16.04-x64.tar.gz"
   - "centos.7-x64.tar.gz"
   - "debian.8-x64.tar.gz"
   - "fedora.24-x64.tar.gz"
   - "rhel.7-x64.tar.gz"
   - "osx.10.12-x64.tar.gz"
  skip_cleanup: true
  on:
    tags: true