os:
  - linux

before_install:
  - sudo apt-get install git-svn

language: csharp
mono: none
dotnet: 2.0.0
script:
 - chmod +x build.sh
 - chmod +x test.sh
 - ./build.sh
 - ./test.sh

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
   - "./src/bin/Release/netcoreapp2.0/ubuntu.16.04-x64/publish"
   - "./src/bin/Release/netcoreapp2.0/centos.7-x64/publish"
   - "./src/bin/Release/netcoreapp2.0/debian.8-x64/publish"
   - "./src/bin/Release/netcoreapp2.0/fedora.24-x64/publish"
   - "./src/bin/Release/netcoreapp2.0/rhel.7-x64/publish"
   - "./src/bin/Release/netcoreapp2.0/osx.10.12-x64"
  skip_cleanup: true
  on:
    tags: true